baidu:
  appId: 15295481
  apiKey: rhfljxaNEKuF7rXEtYhYHXAM
  secretKey: 3RwbOrXTeBCGaIdi4sIVT7itonXgrgGx

spring:
  datasource:
    url: jdbc:mysql://tencent:3306/motoko?characterEncoding=utf-8
    #url: jdbc:mysql://176.122.176.71:3306/varys?characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 12cf0d30
    #username: test
    #password: test
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: club.projectgaia.motoko.utils.MySQL5InnoDBDialectUtf8mb4
logging:
  level:
    club.projectgaia: info
  file: /home/magneto/log/varys.log
  root: INFO
